# Generated by Django 4.0.3 on 2022-04-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_messages_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
